// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOAOWaURpIusl9sz7avuj-bxXeJ6bIKxM',
    appId: '1:994684832326:web:d2252179c8e4f3d5921847',
    messagingSenderId: '994684832326',
    projectId: 'portfolioapp-3b4b5',
    authDomain: 'portfolioapp-3b4b5.firebaseapp.com',
    storageBucket: 'portfolioapp-3b4b5.firebasestorage.app',
    measurementId: 'G-8WQPVR5N78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN4AR-C6PZF8GtzB2odd8d-EfXLAU9ucU',
    appId: '1:994684832326:android:b860c1d6bf803f0e921847',
    messagingSenderId: '994684832326',
    projectId: 'portfolioapp-3b4b5',
    storageBucket: 'portfolioapp-3b4b5.firebasestorage.app',
  );
}
